### ISSUE TITLE
Change project from private to public

### ISSUE THREAD

**Issue by vemv** [nedap/utils.collections#11]
This project has been (intentionally) OSS for a long time: https://clojars.org/com.nedap.staffing-solutions/utils.collections . It supports f-s and speced.def.

I have now reviewed all its PRs, issues and commits and there's no sensitive material within the repo.

So I propose to change this repo from private to public.

**Comment by jwkoelewijn** [comment]
Done :)

**Comment by vemv** [comment]
ty!
