### ISSUE TITLE
`ffirst!` as a uniqueness checking alternative to `ffirst`

### ISSUE THREAD

**Issue by lennartbuit** [nedap/utils.collections#12]
## Context

Datomic returns sets-of-tuples, even exclusively on client.  So when we are pretty sure there are zero-or-one result tuples of exactly one result (say, because we are querying by some unique reference), we end up with `(->> (d/q ...) (first!) (first!))`, or with `ffirst` (without uniqueness checking).

## Task

An analogue to `ffirst` that checks uniqueness

## Acceptance criteria

```clojure
(ffirst! [[:a]]) ;; should return :a
(ffirst! [[:a :b]]) ;; should throw
(ffirst! [[:a] [:b]]) ;; should throw
```

There are some debatable cases:

```clojure
(ffirst! []) ;; ???
```

**Comment by vemv** [comment]
Agree that the debatable case is debatable :) probably it should stay consistent with `first!`'s behavior

**Comment by lennartbuit** [comment]
If we continue the analogy with clojure.core, `ffirst` has [`Same as (first (first x))`](https://github.com/clojure/clojure/blob/ee3553362de9bc3bfd18d4b0b3381e3483c2a34c/src/clj/clojure/core.clj#L99) as its doc string. That would mean that `ffirst!` is `(comp first! first!)` which throws when assert is true, and returns nil when it is not.

**Comment by vemv** [comment]
It sgtm given it's also consistent with https://github.com/nedap/utils.collections/blob/702e31a83586d5ae9fdb2b4fcfa76735d3fbe58a/test/unit/nedap/utils/collections/eager.clj#L65-L71

...Perhaps I'd favor using `-> x first! first!` over a wrapper, for the same reason I'd favor `->> (filter ...) first` over [find-first](https://github.com/weavejester/medley/blob/aedc20f2de93318225479b2f1e2d98be59fc4610/src/medley/core.cljc#L6): it means fewer contracts to keep around and some emphasis in using composable bits consumer-side.

**Comment by lennartbuit** [comment]
>...Perhaps I'd favor using -> x first! first! over a wrapper, for the same reason I'd favor ->> (filter ...) first over find-first: it means fewer contracts to keep around and some emphasis in using composable bits consumer-side.

Yeah, you can ofcourse compose. The proposal here comes more from an 'upgrade' perspective, say you have an instance of `ffirst`, which is pretty common in datomic client, you can easily point to the familiar-looking-but-slightly-safer alternative `ffirst!`.
